### ISSUE TITLE
French and english localization

### ISSUE THREAD

**Issue by benel** [benel/TraduXio#2]
- On the header and footer:
   - change "Concordancier" (fr) and "Concorder" (en) into "Concordance" in both languages. We speak about the object used by people rather than about the computer program.
   - Change "Copyrights" (fr) into "Droits d'auteur".
- On the copyright page:
   - The french localization seems to be missing. Texts can be found on the original [mockup](https://github.com/benel/TraduXio/wiki/copyrights.png).
   - "Report an on-line abuse" (en) is not a correct translation of "Signaler une mise en ligne abusive" (fr). It should be instead something like "Report a copyright abuse".
  - In "Publication of protected work non-comparable to a short quotation" (en), "non-comparable" does not seem to be a correct translation for "non-assimilable" (fr) in a legal context. We should ask a native speaker.

**Comment by trinhtt** [comment]
Korean localization is also needed.

**Comment by Nigozziath** [comment]
## Note
Is the Korean translation really needed ? 
In the last interview with Guillaume Jeanmaire, he asked for a localization, certainly for his students (Koreans learning french with a very good level of French). But the French localization already exists, so why translate into Korean ?

We should ask for more precisions about it next Friday.

**Comment by GAGNAIRE-Romain** [comment]
## Possible scenario

1. The user may choose his preferred languages.
2. The user can visit either the [traduxio website](traduxio.hypertopic.org) or the [traduxio testing website](traduxio.sandbox.hypertopic.org).
3. The interface will adapt to the user's preferred languages based on the ordering he defined on its browser. If there is no suitable localization available, the interface will use a fallback language (_most likely english_).

## Improvement ideas

- use some kind of button or menu to change the interface language instead of having to modify browser settings.

## Tutorial : How to setup preferred languages on Chrome

1. Open Chome's Settings menu, and click on `show advanced settings`
![settings00](https://cloud.githubusercontent.com/assets/11505086/6899740/99aeea12-d702-11e4-83a6-384aee6fe2f5.png)

2. Click on `choose languages`
![settings02](https://cloud.githubusercontent.com/assets/11505086/6899809/fab8774c-d702-11e4-8ec8-fa3c286d6900.png)

3. You can add as many languages as you want using the `add` button
![settings03](https://cloud.githubusercontent.com/assets/11505086/6899823/10884eda-d703-11e4-8602-fd73c68f8230.png)

4. Here is an example showing the addition of Korean
![settings04](https://cloud.githubusercontent.com/assets/11505086/6899841/2adf1570-d703-11e4-813b-de45ce5b832a.png)

5. You can then sort languages as you want
![settings05](https://cloud.githubusercontent.com/assets/11505086/6899864/57857196-d703-11e4-9e72-2595cfed3ccb.png)

**Comment by ammelanie-utt** [comment]
Le scénario nous semble valide et semble répondre aux attentes du client. La gestion des langues depuis le navigateur nous semble être le plus naturelle, et suffisant dans un premier temps par rapport à la gestion des langues sur l'interface.

Nous n'avons pas vu la nécessité de faire de maquettes. Le ticket est donc passé de validation des scénarios à "Tests de recette".

**Comment by cyprieng** [comment]
Maquette
-----------

Version française :
![mock2](https://cloud.githubusercontent.com/assets/2521188/7027099/fe157d6c-dd4d-11e4-94fd-1c6c6d26f04d.png)


Version anglaise :
![mock2](https://cloud.githubusercontent.com/assets/2521188/7027171/67c5b4e8-dd4e-11e4-853a-46ce78488a64.png)

Version portugaise :
![mock2](https://cloud.githubusercontent.com/assets/2521188/7027274/f7925356-dd4e-11e4-8576-54d059ef82d5.png)

**Comment by ammelanie-utt** [comment]
Résultat de l'entretien : 

* La traduction n'est pas pour les étudiants en traduction mais plutôt pour des étudiants anglais qui n'utilisent pas le site à cause de la langue française par défaut
* Le coréen n'a pas l'air d'être un impératif en soi, l'anglais semble être la priorité
* Le bandeau de sélection  au sein de l'interface est "mieux" mais non nécessaire dans un premier temps car plus compliqué. Visiblement le but est bien de s'adapter à la langue de l'utilisateur : l'utilisation des paramètres du navigateur suffirait donc !

**Comment by stombre** [comment]
#Test de recette
Test de recette a utilisé sur Capybara, On a mis la langue française même si le navigateur a comme préférence le coréen pour ne pas mettre en anglais l'interface pour les étudiants de Guillaume Jeanmaire.

```ruby
require 'spec_helper'

feature 'Localization' do

scenario 'french' do
	prefer_language('ko;q=1,fr-FR;q=0.9,fr;q=0.8,en;q=0.7')
	visit '/'
	click_on  'Ajouter une oeuvre'
	expect(page).to have_content 'Titre'
end

scenario 'english' do
	prefer_language('en-au,en-us,en,fr')
	visit '/'
	click_on  'Add a work'
	expect(page).to have_content 'Title'
end

end
```

**Comment by SAMIEMEHEZA** [comment]
Le test précédent ne marchait pas sur la version en production.

Ceci était dû au fait que le placeholder 'Titre' n'était pas trouvé par la fonction expect(page).to have_content. Le second problème venait du fait que la fonction visit ne parcourait pas la bonne page.

Voici la nouvelle version qui a été testée (et fonctionne pour le français, l'anglais n'étant pas encore implémenté sur la version en production) :

```javascript
require 'spec_helper'

feature 'Localization' do
    
    scenario 'french' do
        prefer_language('ko;q=1,fr-FR;q=0.9,fr;q=0.8,en;q=0.7')
        visit '/works/'
        click_on  'Ajouter une oeuvre'
        expect(page).to have_content 'Oeuvre originale'
    end
    
    scenario 'english' do
        prefer_language('en-au,en-us,en,fr')
        visit '/works/'
        click_on  'Add a work'
        expect(page).to have_content 'Original work'
    end
    
end
```

**Comment by DavyPierre** [comment]
Tests avec Capybara en cours.
Tests à continuer.
Soucis avec le matériel

**Comment by Luwangel** [comment]
Nos tests de validation de la fonctionnalité ont révélé lundi un problème au niveau du bouton "Ajouter une oeuvre". En effet celui-ci n'apparaissait plus dans la version en développement. Nous l'avons reporté directement dans la pull request et ce problème semble avoir été résolu depuis. 

Il est donc nécessaire de relancer les tests sur la version corrigée afin de valider définitivement cette fonctionnalité.

**Comment by DavyPierre** [comment]
Compte rendu sur cette fonctionnalité le 24/04:
-Le client propose une traduction audiovisuelle

est-ce possible? Difficile/cher à implémenter?

**Comment by adeprez** [comment]
Fonctionnalité validée par les tests.
